### ISSUE TITLE
[Question] Will it be possible to create demo videos of libgdx projects using this extension?

### ISSUE THREAD

**Issue by rinold** [libgdx/gdx-video#1]
It will be great not to grab the screenshots manually and then convert them using third-party tools to video. If possible it will be very useful to create such videos using this extension with pretty interface, and awesome if it will be possible to collect audio at the same time, at least on desktop :)

So the question is - is it possible? I mean not now, but is it possible for implementation in general? May be you already have some plans about it?

And of course thanks for a great work :+1:

**Comment by gjroelofs** [comment]
The intent of this extension is just to support decoding & displaying of video.

While it may be possible, through FFMPEG, it's probably best to just use a third-party recording tool.
Especially given the fact that recording then can also only be done in a select few codecs (GPL restrictions).

The only use case I see which cannot be solved easily through external tools is recording ingame gameplay done by the player, to be used internally in the game. However, in that case I would suggest just keeping track of the actions of the player and playing those back.
