### ISSUE TITLE
Setting up gdx-video?

### ISSUE THREAD

**Issue by YanJenHuang** [libgdx/gdx-video#21]
Can anyone give me a hint how to set up this library?
I try many times and still not work.
I set the "Gradle dependency declarations" as readme said in build.gradle but still not working.

**Comment by Robbiedobbie** [comment]
Currently, the build server is not yet building these projects. (This is a WIP).

This means that you have to download the source, and build it yourself. Since the native files are hard to build, we provide a pre-built version, which you can find in #2.

Good luck!

**Comment by YanJenHuang** [comment]
thank you~
