### ISSUE TITLE
Hardware accelerated H264 video decoding on Windows 10 with Intel HD Graphics (Cherry Trail)

### ISSUE THREAD

**Issue by SonicACCEL** [libgdx/gdx-video#27]
I wonder if there is any best practices or recommendations for video playback on the newest Intel HD graphics as far as hardware accelerated video decoding. 

Is H264 the recommended format?

**Comment by Robbiedobbie** [comment]
I can't really tell for sure. It depends on what codecs you're running, but more importantly, what decoders ffmpeg is using. You can probably find the information you need in the ffmpeg documentation. The precompiled version for this project is not using any hardware acceleration.
