### ISSUE TITLE
Error: Failed to resolve: com.badlogicgames.gdxvideo:gdx-video:0.0.1

### ISSUE THREAD

**Issue by appkovacs** [libgdx/gdx-video#30]
I am looking for YouTube video playing solutions in libGDX, so I have found this repo.
Can you please explain in a few sentences, how can it used?
Thanks in advance!

**Comment by Robbiedobbie** [comment]
You'd have to download the youtube video and convert it to one of the formats that the precompiled ffmpeg  and android can play. 

The error that you put in the title is caused by #2. You can read this issue for how to solve it.

**Comment by appkovacs** [comment]
Can you give me some tutorials, please?

**Comment by appkovacs** [comment]
About usage, use cases maybe.

**Comment by Robbiedobbie** [comment]
Youtube -> streaming -> #7 ?
