### ISSUE TITLE
Can't generate .jar files for Android and Linux desktops

### ISSUE THREAD

**Issue by binhor009** [libgdx/gdx-video#37]
Hello, I have been getting nothing every time I try to generate the .jar files.
I think the error is mine.... Would you share with me the .jar file for Linux, Android, Windows and Mac as possible as you can?

Thanks....

**Comment by Robbiedobbie** [comment]
All the jars needed can be found here: https://www.dropbox.com/sh/q7vvkcy81uf8h24/AAAclKOYTJnNHixeaFVSuMvSa?dl=0

**Comment by binhor009** [comment]
Thanks!
