### ISSUE TITLE
Gradle Coordinates are wrong

### ISSUE THREAD

**Issue by JuKu** [libgdx/gdx-video#41]
Your gradle coordinates, shown on ReadMe, are wrong, gradle cannot find them anymore.

**Comment by Robbiedobbie** [comment]
The readme was written in preparation of how it will become available. Unfortunately, since the buildserver still hasn't been set up correctly, no artifacts have yet been published to the artifact repository.

**Comment by JuKu** [comment]
@Robbiedobbie Thanks for your answer!
But this means, this extension is nevertheless up to date and compatible with the newest libGDX version?

**Comment by Robbiedobbie** [comment]
I haven't tried it recently, but it has very little dependencies on libgdx, so I don't expect any issues.

**Comment by JuKu** [comment]
Thanks! :D

**Comment by JuKu** [comment]
@Robbiedobbie And were can i find desktop-natives?

**Comment by JuKu** [comment]
Thanks! :D
