### ISSUE TITLE
Android - Failed to Resolve

### ISSUE THREAD

**Issue by vaaneeunbnd** [libgdx/gdx-video#59]
Hello, 

Hope your day is going well. I was trying to add the gdx-video library to the Gradle build file, however, I am getting the error message - Failed to resolve: com.badlogicgames.gdxvideo:gdx-video-android:1.9.12.

I would be grateful if someone can help me with this.

Thanks

**Comment by SimonIT** [comment]
Sadly, there is nothing I can do about it. I want to upload it, but @Tom-Ski has to make some sonatype stuff to get it working.
I'm closing this, because this is a duplicate of #51
