### ISSUE TITLE
Rendering Video Texture on 3D Plane

### ISSUE THREAD

**Issue by vaaneeunbnd** [libgdx/gdx-video#60]
Hello, 

I wanted to render video texture on 3d plane. I tried doing for 3D for the modelbatch using the 2D example provided in the library, however, I got the GL thread error. 

I would be grateful if someone can help me with this.

Thanks :)

**Comment by SimonIT** [comment]
Please join the [community](https://libgdx.com/community/) for questions. This is an issue tracker and not a support forum.

A gl thread error indicates, that you are not drawing from the rendering thread.
