### ISSUE TITLE
Black screen while play on Android hardware device

### ISSUE THREAD

**Issue by gmanrainy** [libgdx/gdx-video#64]
I am trying to draw a video into a sprite, but after starting to play the video, I see one frame from the video for a split second and then just a black screen
And at the same time on AVD everything work fine
I tried different options and the result is the same, tried draw video to mash and replace MediaPlayer to ExoPlayer, but nothing

**Comment by SimonIT** [comment]
New snapshot with the fix should be available

**Comment by gmanrainy** [comment]
Checked and everything works well 👍
