### ISSUE TITLE
update to current libgdx and include desktop loopback support

### ISSUE THREAD

**Issue by thelsing** [libgdx/gdx-video#71]
Hello,

could you please add the loopback support from https://github.com/SimonIT/gdx-video update to current libgdx and publish a snapshot?

I would build it myself with jitpack.io but the native libs make this quite hard if not impossible.

**Comment by SimonIT** [comment]
I'm sorry to say that my attempts to get looping on desktop to work were not successful. You see in my fork only all attempts I made, but they don't work. I would appreciate any help

**Comment by SimonIT** [comment]
I closed this because it's a duplicate to #67
