### ISSUE TITLE
Is it possible to run the Desktop sample too?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [libgdx/gdx-video#76]
I tried to find all files with "main" in them, but all of them just showed a black window, that closes when I press in it....

**Comment by Frosty-J** [comment]
Hi, I'm not sure what you mean? Easiest way to try it would probably be to copy [GdxVideoTest](https://github.com/libgdx/gdx-video/blob/master/test/core/src/main/java/com/badlogic/gdx/video/test/GdxVideoTest.java) into your own project, along with the [sample WebM](https://github.com/libgdx/gdx-video/blob/master/test/assets/libGDX%20-%20It's%20Good%20For%20You!.webm).

Most videos won't work on desktop as there's no H.264+AAC decoding support, but VP9 (or VP8 but I don't know why you'd use that) in an MKV container works fine. Vorbis audio is supported, but best have it as a separate file using `Music` so you can keep the audiosync in check.

**Comment by AndroidDeveloperLB** [comment]
I mean that launching the app on PC, using every possible class that has "main" in it, resulted in a black screen, making the sample not quite showing what it's supposed to do on PC. 
I think only on Android it works well.

Here, a video to show you what I see (when launching the DesktopLauncher, as GdxVideoTest doesn't have "main" function) :
[studio64_M7weJh48yZ.zip](https://github.com/libgdx/gdx-video/files/9638227/studio64_M7weJh48yZ.zip)


As for support of video codecs, I'm very sure my PC can play them. I already have a codec pack installed (k-lite).
When pressing the black content, I get this in the logs:

```
Caused by: com.badlogic.gdx.utils.GdxRuntimeException: Unable to read file for extraction: gdx-video-desktop64.dll
```

**Comment by Frosty-J** [comment]
Running `DesktopLauncher` (or `Lwjgl3Launcher` - I'm going to refer to the latter as `DesktopLauncher` for simplicity) is the correct way to start a libGDX application on desktop.

Have you added the desktop Gradle dependency? `implementation "com.badlogicgames.gdx-video:gdx-video-lwjgl3:1.3.2-SNAPSHOT"`, or `lwjgl` instead of `lwjgl3` if your `DesktopLauncher` uses `LwjglApplication`.

MP4 was actually replaced in 4b4339a3d08c38f6bdae4f3c7adaa77220db8b8e for compatibility. Personally, I use H.264 MP4 for non-desktop targets.

**Comment by AndroidDeveloperLB** [comment]
@Frosty-J Isn't it enough to clone the project and run it? Why isn't the dependency in the project, and I need to add it?
As for DesktopLauncher , that's what I launched, as you can see on the video.

**Comment by AndroidDeveloperLB** [comment]
OK thanks. 
Please consider adding a note in the desktop class "DesktopLauncher" that says that it's currently not working, if you failed to open it normally.
