### ISSUE TITLE
failed to resolve com.badlogicgames.gdx video:gdx-video-android:0.0.1

### ISSUE THREAD

**Issue by aklisanic** [libgdx/gdx-video#8]
I am getting this and similar errors for all gdx-video related libs I included in my project's gradle build scripts. I followed instructions on main page. Is there anything else I need to do?

**Comment by mnn** [comment]
I have same problem. It seems the library is missing from repository - no gdx-video @ https://oss.sonatype.org/content/repositories/releases/com/badlogicgames/. I wonder if it is no longer supported/compatible or what is the cause.

**Comment by Robbiedobbie** [comment]
The libs are indeed not yet in the maven repos. See issue #2. Unfortunately, there were a lot of issues getting it to run on the libgdx build server. Then a period came where everybody was extremely busy. We unfortunately still are. This christmas I was planning on trying to run the build on travis-ci. Until then, you'll have to build the library yourself. A precompiled package with the native libraries can be found in issue #2.

**Comment by mnn** [comment]
Thank you for response. I'm glad the project is alive :).

**Comment by badlogic** [comment]
Passt fuer mich. Hast du mit Kern, Klampfl und Schulze auch geredet?

Mario

**Comment by aklisanic** [comment]
Yep. Solution from #2 looks OK for now. Good luck with making it work on server.
