### ISSUE TITLE
`isPlaying()` behaviour across backends

### ISSUE THREAD

**Issue by Frosty-J** [libgdx/gdx-video#86]
Have I got it right that `isPlaying()` returns true when paused on desktop, but false on the other backends?

I discovered this when I was testing pause functionality and couldn't get the pause status out of the desktop video player.

**Comment by SimonIT** [comment]
Hmm yeah, that shouldn't be. I think the easiest way is to change it to `playing && !paused`

**Comment by SimonIT** [comment]
Changed in f3567a00809da697f0a320cba95e1bc295a51d12
