### ISSUE TITLE
Not in the Sonatype Repository at all: Add the version for the Dependency in the Readme

### ISSUE THREAD

**Issue by WiFisunset** [libgdx/gdx-video#92]
This isn't in the Sonatype Repository at all.

**Comment by Frosty-J** [comment]
1.3.2-SNAPSHOT

https://oss.sonatype.org/#nexus-search;gav~com.badlogicgames.gdx-video~gdx-video~~~~kw,versionexpand

**Comment by anigart** [comment]
I'm getting below 404 when trying to download the library jar... is there any place where I can download the build without having to compile everything from scratch (incl. the natives)? Would like to try it on desktop.

Path /com/badlogicgames/gdx-video/gdx-video/1.3.2-SNAPSHOT/gdx-video-1.3.2-20240331.124500-19-library.jar not found in local storage of repository "Snapshots" [id=snapshots]
